#!/usr/bin/python3

import curses
from curses_helper.mainscreen import MainScreen
from curses_helper.util import center_start
__author__ = 'Kellan Childers'


def app(stdscr):
    # Ensures a clean visual space.
    stdscr.clear()
    curses.curs_set(False)

    # Sets the three main colors for the app screen.
    # First color: text. Second color: background.
    curses.init_pair(1, curses.COLOR_WHITE, curses.COLOR_BLUE)
    curses.init_pair(2, curses.COLOR_BLACK, curses.COLOR_WHITE)
    curses.init_pair(3, curses.COLOR_BLACK, curses.COLOR_BLACK)
    # Set the background of the app to white.
    stdscr.bkgd(' ', curses.color_pair(2))

    console_height, console_width = stdscr.getmaxyx()
    _, title_x = center_start(console_height, console_width, 1, 28)
    stdscr.addstr(0, title_x, "Roguelike by Kellan Childers", curses.A_BOLD | curses.A_UNDERLINE)

    stdscr.refresh()

    main_screen = MainScreen(console_height, console_width)
    main_screen.show_intro()
    main_screen.start_shopping_list()

    while True:
        main_screen.clear_screen()
        main_screen.do_command()

if __name__ == "__main__":
    # curses.wrapper ensures that program will always fully exit from curses mode if an error occurs.
    curses.wrapper(app)
